export const modes = [
 {id:'mix',name:'Modo previa',description:'Una mezcla de todo. Que decida la noche.',min:3},
 {id:'vote',name:'El señalado',description:'Vota en secreto. Luego toca dar explicaciones.',min:3},
 {id:'paranoia',name:'Bajo cuerda',description:'Tu nombre ha salido. La pregunta… ya veremos.',min:3},
 {id:'faker',name:'El infiltrado',description:'Alguien no sabe de qué va esto. Cázalo.',min:3},
 {id:'bluff',name:'Mucho cuento',description:'Una verdad tuya. Un montón de mentiras suyas.',min:3},
 {id:'speed',name:'Sin pensarlo',description:'Tres respuestas. Ocho segundos. Poco filtro.',min:2},
 {id:'match',name:'Cruce de miradas',description:'Elige a alguien. Solo salen los matches.',min:3},
 {id:'never',name:'Aquí se confiesa',description:'Yo nunca, pero aquí nadie viene de santo.',min:2},
 {id:'ten',name:'Tiene un pero',description:'Era un diez… hasta que contó eso.',min:2},
 {id:'defend',name:'Defiende lo indefendible',description:'Véndenos esa red flag en quince segundos.',min:3}
];
// Textos originales. El nivel máximo incluye las preguntas de los anteriores.
const lines = {
vote:[
'0|¿Quién dice «estoy llegando» cuando todavía está en la ducha?',
'0|¿Quién convertiría una caña en volver a casa con churros?',
'0|¿Quién se iría de la zona de bares sin haber pisado el bar donde habíamos quedado?',
'0|¿Quién se haría amigo de todo el autobús de vuelta?',
'0|¿Quién asegura que conoce un sitio y nos lleva cuarenta minutos andando?',
'1|¿Quién cruzaría la ciudad a las cuatro por un «vente»?',
'1|¿Quién dice que pasa de relaciones y analiza un «jajaja» cuarenta minutos?',
'1|¿Quién sería el primero en volver con su ex y llamarlo «cerrar etapas»?',
'1|¿Quién podría tener dos citas el mismo día sin salir de su barrio?',
'1|¿Quién tiene más labia por WhatsApp que en persona?',
'2|¿Quién es más probable que tenga un rollo secreto del que no sabemos nada?',
'2|¿Quién acabaría liándose con alguien después de decir «yo con esa persona jamás»?'],
paranoia:[
'0|¿A quién elegirías para improvisar un plan que dure hasta mañana?',
'0|¿Quién te convencería de perder el último autobús?',
'0|¿Quién sería tu mejor cómplice para escapar de una cita aburrida?',
'1|¿Con quién de aquí tendrías una cita que no contarías en el grupo?',
'1|¿Quién te ha sorprendido más para bien desde que lo conoces?',
'1|¿Quién crees que liga sin darse cuenta?',
'1|¿Con quién aceptarías un plan sin preguntar cuál es?',
'2|¿Con quién de aquí crees que habría más química en una cita?',
'2|¿Quién te pondría más nervioso si te dijera que le gustas?',
'2|¿Con quién te quedarías hablando a solas cuando se fuera todo el mundo?'],
faker:[
'0|¿Qué excusa pondrías para irte pronto de una fiesta?',
'0|¿Qué llevarías a una previa en un piso sin sillas?',
'0|¿Qué dirías después de perder el último autobús?',
'0|¿Qué pedirías para desayunar después de salir?',
'1|¿Qué frase de app de citas te haría cerrar la conversación?',
'1|¿Qué detalle te haría pedir una segunda cita?',
'1|¿Qué excusa pondrías para escribirle a un ex?',
'1|¿Qué mensaje mandarías después de un beso inesperado?',
'2|¿Qué frase arruinaría un momento de tonteo?',
'2|¿Qué objeto te daría vergüenza encontrar en tu bolsillo en una cita?'],
bluff:[
'0|La excusa más mala que he dado para no salir fue…',
'0|El sitio más raro donde me he quedado dormido fue…',
'0|Mi peor compra para impresionar a alguien fue…',
'0|La mentira más absurda que me creyeron fue…',
'1|Mi mensaje de tonteo más vergonzoso decía…',
'1|La peor excusa que me dieron para no repetir una cita fue…',
'1|Mi intento más ridículo de llamar la atención fue…',
'1|Lo más absurdo que hice por un crush fue…',
'2|Una situación de intimidad que terminó en risas fue…',
'2|Mi momento más incómodo con un rollo fue…'],
speed:[
'0|Di tres excusas para llegar una hora tarde a una previa.',
'0|Di tres cosas que desaparecen en un piso compartido.',
'0|Di tres destinos posibles después de «una y nos vamos».',
'0|Di tres cosas que jamás deberías decir al casero.',
'1|Di tres mensajes que no deberías mandar a tu ex a las cinco.',
'1|Di tres señales de que la cita está saliendo fatal.',
'1|Di tres excusas para quedarte un rato más con un crush.',
'1|Di tres red flags que alguna vez has ignorado.',
'2|Di tres frases que cortan cualquier tonteo.',
'2|Di tres cosas que esconderías antes de que llegue tu cita.'],
match:[
'0|¿Con quién compartirías el último taxi?',
'0|¿Con quién te irías de escapada sin preparar nada?',
'0|¿Con quién te quedarías charlando hasta el desayuno?',
'0|¿Quién sería tu pareja en un concurso de improvisar excusas?',
'1|¿Con quién tendrías una segunda primera cita?',
'1|¿A quién invitarías a tomar algo a solas?',
'1|¿Con quién fingirías ser pareja para una broma?',
'2|¿Con quién te gustaría descubrir si hay química?',
'2|¿A quién propondrías seguir el plan cuando todos se fueran?',
'2|¿Con quién aceptarías una cita sorpresa esta semana?'],
ten:[
'0|Es un diez, pero dice «vivo al lado» y está a noventa minutos.',
'0|Es un diez, pero reserva una mesa para dos y lleva a seis amigos.',
'0|Es un diez, pero aplaude cuando aterriza el avión.',
'0|Es un diez, pero manda audios de siete minutos.',
'1|Es un diez, pero mantiene una racha de mensajes con su ex.',
'1|Es un diez, pero te llama «bro» después del primer beso.',
'1|Es un diez, pero tarda tres días en responder y siempre está online.',
'1|Es un diez, pero te lleva al mismo bar que a todos sus rollos.',
'2|Es un diez, pero después de liaros te pide consejo sobre otra persona.',
'2|Es un diez, pero te pregunta el signo antes de besarte.'],
defend:[
'0|Siempre llega cuarenta minutos tarde, pero dice que es parte de su encanto.',
'0|No sale de su barrio porque «lo bueno está aquí».',
'0|Manda un Bizum de 37 céntimos después de cada plan.',
'0|Dice que controla la música y pone su propia playlist de gimnasio.',
'1|Sigue compartiendo Netflix con su ex.',
'1|Vive al otro extremo de la ciudad y siempre te toca ir a ti.',
'1|Llama «fluir» a no hacer planes con más de diez minutos de margen.',
'1|Tiene una foto con un ex en todas sus redes porque «salgo bien».',
'2|Te presenta como colega después de tres meses de citas.',
'2|Solo propone veros cuando termina el resto de sus planes.']
};
export const prompts=Object.fromEntries(Object.entries(lines).map(([mode,rows])=>[mode,rows.map((line,i)=>({id:mode+'-'+i,level:Number(line[0]),text:line.slice(2)}))]));

